version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
       GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx4048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "buildSrc/src/main/java/GradleDepenedencies.kt"}}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "buildSrc/src/main/java/GradleDepenedencies.kt"}}
      - run:
          name: run unit test
          command: ./gradlew testReleaseUnitTest --info
      - run:
          name: Build apk
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk_output
      - store_artifacts:
          path: app/build/reports/tests
          destination: test_results